import {
    Waves,
    Ship,
    Camera,
    Fish,
    Footprints,
    Utensils,
    Flower2,
    Anchor,
    LifeBuoy,
} from "lucide-react"

export const activities = [
    { id: "surfing", title: "Surfing", color: "from-teal-400 to-blue-500", icon: Waves, svg: "/svgs/Surfing.svg", description: "Ride the waves of the Atlantic. Perfect for beginners and pros alike." },
    { id: "canoeing", title: "Canoeing", color: "from-cyan-400 to-blue-500", icon: Ship, svg: "/svgs/Canoeing.svg", description: "Paddle through the serene lagoon waters and explore the mangroves." },
    { id: "photography", title: "Photography", color: "from-purple-400 to-pink-500", icon: Camera, svg: "/svgs/Photography.svg", description: "Capture the stunning golden hour, vibrant culture, and scenic landscapes." },
    { id: "diving", title: "Diving", color: "from-blue-500 to-indigo-600", icon: Anchor, svg: "/svgs/Diving.svg", description: "Explore the underwater world and discover marine life off the coast." },
    { id: "fishing", title: "Fishing", color: "from-sky-400 to-blue-600", icon: Fish, svg: "/svgs/Fishing.svg", description: "Join local fishermen or charter a boat for a deep-sea fishing adventure." },
    { id: "beach-walks", title: "Beach Walks", color: "from-amber-300 to-orange-500", icon: Footprints, svg: "/svgs/BeachWalks.svg", description: "Take long, peaceful strolls along the pristine white sands of Ilashe." },
    { id: "picnicking", title: "Picnicking", color: "from-green-400 to-emerald-600", icon: Utensils, svg: "/svgs/Picnicking.svg", description: "Enjoy a delicious meal with friends and family in a beautiful beach setting." },
    { id: "meditation", title: "Meditation", color: "from-violet-400 to-fuchsia-500", icon: Flower2, svg: "/svgs/Meditation.svg", description: "Find your inner peace with sunrise or sunset meditation sessions by the ocean." },
    { id: "kayaking", title: "Kayaking", color: "from-yellow-400 to-orange-500", icon: Ship, svg: "/svgs/Kayaking.svg", description: "Navigate the waterways at your own pace in a single or double kayak." },
    { id: "snorkeling", title: "Snorkeling", color: "from-pink-400 to-rose-500", icon: LifeBuoy, svg: "/svgs/Snorkeling.svg", description: "Swim on the surface and observe the fascinating sea life below." },
    { id: "kite-surfing", title: "Kite Surfing", color: "from-teal-300 to-emerald-500", icon: Waves, svg: "/svgs/Kite-surfing.svg", description: "Harness the power of the wind for an adrenaline-pumping experience." },
    { id: "horse-riding", title: "Horse Riding", color: "from-cyan-300 to-sky-500", icon: Ship, svg: "/svgs/Horseriding.svg", description: "Experience the freedom of riding a horse along the shoreline." },
]

export interface Place {
    id: number
    name: string
    activityId: string
    image: string
    description: string
    openingTime: string
    price: string
    isFree: boolean
    contact: string
    location: string
}

export const places: Place[] = [
    {
        id: 1,
        name: "Pop Ilashe",
        activityId: "surfing",
        image: "/images/beach-club.jpg",
        description: "Exclusive beach club with professional instructors and equipment rental.",
        openingTime: "8:00 AM - 6:00 PM",
        price: "",
        isFree: true,
        contact: "+234 803 300 6319",
        location: "Plot 10, Ilashe Beach",
    },
    {
        id: 2,
        name: "Lagoon Watersports Center",
        activityId: "canoeing",
        image: "/images/watersports.jpg",
        description: "Rent canoes and explore the calm lagoon waters. Guided tours available.",
        openingTime: "9:00 AM - 5:00 PM",
        price: "₦5,000 / hour",
        isFree: false,
        contact: "+234 800 987 6543",
        location: "Jetty 4, Ilashe Lagoon Side",
    },
    {
        id: 3,
        name: "Sunset Point",
        activityId: "photography",
        image: "/images/sunset.jpg",
        description: "The perfect spot for sunset photography. Open to all visitors.",
        openingTime: "Open 24 Hours",
        price: "Free",
        isFree: true,
        contact: "N/A",
        location: "West End, Ilashe Beach",
    },
    {
        id: 4,
        name: "Deep Blue Dive Shop",
        activityId: "diving",
        image: "/images/diving.jpg",
        description: "Certified PADI dive center offering courses and guided dives.",
        openingTime: "8:00 AM - 4:00 PM",
        price: "₦25,000 / dive",
        isFree: false,
        contact: "+234 700 DIVE NOW",
        location: "Main Beach Road",
    },
    {
        id: 5,
        name: "Local Fishermen's Wharf",
        activityId: "fishing",
        image: "/images/fishing.jpg",
        description: "Join local fishermen for a traditional fishing experience.",
        openingTime: "5:00 AM - 12:00 PM",
        price: "Negotiable",
        isFree: false,
        contact: "Ask at the Jetty",
        location: "East Village",
    },
    {
        id: 6,
        name: "The Long Stretch",
        activityId: "beach-walks",
        image: "/images/beach-walk.jpg",
        description: "Miles of uninterrupted sand perfect for morning or evening walks.",
        openingTime: "Open 24 Hours",
        price: "Free",
        isFree: true,
        contact: "N/A",
        location: "Along the coastline",
    },
    {
        id: 7,
        name: "Palm Grove Picnic Area",
        activityId: "picnicking",
        image: "/images/picnic.jpg",
        description: "Shaded area with tables and benches. Bring your own food or order from nearby stalls.",
        openingTime: "10:00 AM - 7:00 PM",
        price: "₦2,000 entry fee",
        isFree: false,
        contact: "+234 800 PICNIC",
        location: "Central Park Area",
    },
    {
        id: 8,
        name: "Zen Garden",
        activityId: "meditation",
        image: "/images/meditation.jpg",
        description: "A quiet, secluded garden dedicated to mindfulness and meditation.",
        openingTime: "6:00 AM - 8:00 PM",
        price: "Donation based",
        isFree: true,
        contact: "N/A",
        location: "Behind the Community Center",
    },
    {
        id: 9,
        name: "Lagoon Kayaks",
        activityId: "kayaking",
        image: "/images/kayak.jpg",
        description: "Single and double kayaks for rent. Life jackets included.",
        openingTime: "9:00 AM - 6:00 PM",
        price: "₦4,000 / hour",
        isFree: false,
        contact: "+234 800 KAYAK",
        location: "Lagoon Jetty",
    },
    {
        id: 10,
        name: "Reef Snorkel Tours",
        activityId: "snorkeling",
        image: "/images/snorkel.jpg",
        description: "Boat trips to the best snorkeling spots near the reef.",
        openingTime: "10:00 AM - 3:00 PM",
        price: "₦10,000 / trip",
        isFree: false,
        contact: "+234 800 REEF",
        location: "Main Jetty",
    },
    {
        id: 11,
        name: "Wind Riders Club",
        activityId: "kite-surfing",
        image: "/images/kitesurf.jpg",
        description: "Kite surfing lessons and equipment rental for all levels.",
        openingTime: "11:00 AM - 5:00 PM (Wind dependent)",
        price: "₦20,000 / lesson",
        isFree: false,
        contact: "+234 800 WIND",
        location: "North Point",
    },
    {
        id: 12,
        name: "Beach Stables",
        activityId: "horse-riding",
        image: "/images/horse.jpg",
        description: "Guided horse riding tours along the beach at sunset.",
        openingTime: "4:00 PM - 7:00 PM",
        price: "₦8,000 / ride",
        isFree: false,
        contact: "+234 800 HORSE",
        location: "South End Stables",
    },
]
